### ISSUE TITLE
Consider adding quarto-drop into Quarto extensions listing

### ISSUE THREAD

**Issue by parmsam** [r-wasm/quarto-drop#2]
Love the extension! Would be nice addition to the Quarto extension listing. 
- https://quarto.org/docs/extensions/listing-revealjs.html
- https://github.com/quarto-dev/quarto-web/tree/main/docs/extensions/listings

**Comment by georgestagg** [comment]
Thanks! Added a PR: https://github.com/quarto-dev/quarto-web/pull/1273

**Comment by georgestagg** [comment]
Merged! 🎉

Drop should be listed under https://quarto.org/docs/extensions/listing-revealjs.html now.
