### ISSUE TITLE
Possible to run a simple Shiny app?

### ISSUE THREAD

**Issue by joshcullen** [r-wasm/quarto-drop#7]
This seems like a really great extension, especially for teaching purposes!

Not sure if it's possible to run a Shiny app with the way things are set up, but I received a `Error in utils::browseURL(appUrl) : 'browser' must be a non-empty character string` and wasn't able to resolve the error by specifying `shinyApp(ui, server, options = list(launch.browser = TRUE))`. Do you know if there's an argument that can be specified to resolve this? Below is the example code I used for the app:

```
library(shiny)

ui <- fluidPage(
  titlePanel("Old Faithful"),
  sidebarLayout(
    sidebarPanel = sidebarPanel(
      sliderInput(inputId = "bins", label = "Number of bins:",
            min = 1, max = 50, value = 30)
    ),
    mainPanel = mainPanel(
      plotOutput("distPlot")
    )
  )
)

server <- function(input, output, session) {
  
     output$distPlot <- renderPlot({
      # generate bins based on input$bins from ui.R
      wait <- faithful[, 2] 
      bins <- seq(min(wait), max(wait), length.out = input$bins + 1)
      
      # draw the histogram with the specified number of bins
      hist(wait, breaks = bins, col = 'darkgray', border = 'white')
   })
     
}
```

**Comment by coatless** [comment]
@joshcullen approach to be taken would likely be to use the [`{quarto-shinylive}`](https://github.com/quarto-ext/shinylive) extension and create a code cell that has the editor and viewer components, e.g.

````md
```{shinylive-r}
#| standalone: true
#| components: [editor, viewer]

# app code from your example
```
````

Alternatively, you can embed the [shinylive editor](https://shinylive.io/r/editor) website directly into a presentation, c.f. 

````md
## shinylive REPL

```{=html}
<iframe allow="cross-origin-isolated" style="display:block; margin: 0 auto;" width="90%" height="75%" src="https://shinylive.io/r/editor">
</iframe>
```
````

Swap the `src` part of the `iframe` with the embedded shiny app if needed.

**Comment by georgestagg** [comment]
Yes, I definitely think the right way to do this is using shinylive, as @coatless describes above.

The intention for this extension is really just to provide a simple scratch pad for impromptu scripting, rather than supporting complex applications such as Shiny apps. For that reason I'm going to close this issue in favor of pointing towards the [quarto-shinylive](https://github.com/quarto-ext/shinylive) extension.
